user: "la20fo09"
token: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJjOWY3MjgxYS1iODhiLTRjYTktYjZiOS05OTcxZWMxNjlmYjIifQ=="
project: "Unsupervised-chameleon"